spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postdb
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080